### ISSUE TITLE
Rich text posts

### ISSUE THREAD

**Issue by jkubacki** [fantasygame/campaigns#19]
Use some kind of gem to use WYSIWYG editor in post form

**Comment by gogi** [comment]
I've used gem bootsy: 498671b2d75f956654ff52cbb0915a4be734a53d
and added it to Post and Idea form: 76ce60738f98ad23f84255d80164de93d96022ad 6bb573e625913b7f76b933e57b6fe51e78a8d9d2

**Comment by jkubacki** [comment]
This is freaking AWESOME! Clean & minimalistic.

Checked for XSS scripting and it's clean. Adding image from external link works nicely. Thank You!
