### ISSUE TITLE
Items pagination

### ISSUE THREAD

**Issue by jkubacki** [fantasygame/campaigns#21]
Use pagination for items list (in campaign items and user view)

**Comment by gogi** [comment]
Done for campaign items
40482e93f1aebf49991ee09237cd0c16ec01360d

**Comment by gogi** [comment]
Done for items in hero view. Only it bubbles up to the top of next page and I will try to fix it before closing this issue.

aa46a4792060acd47eef60c20801ee3657e98b0e

**Comment by gogi** [comment]
Moved hero items to the top of page

260e03a24e4074db807bbf4cd5af77ea35555510
