### ISSUE TITLE
Hero edit atuhorization

### ISSUE THREAD

**Issue by jkubacki** [fantasygame/campaigns#22]
Every campaign member should be able to edit BN (non user hero) heroes.

**Comment by gogi** [comment]
Policy changed. All members can change NPC hero.

59306e7ac5d0ce404d44e6eb7347f16e06196c32

**Comment by gogi** [comment]
Need to add specs?

**Comment by jkubacki** [comment]
Would be nice ;)

On Tue, Jun 16, 2015 at 12:55 PM, Małgorzata Grobelska <
notifications@github.com> wrote:

> Need to add specs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fantasygame/campaigns/issues/22#issuecomment-112384814>
> .
>



-- 
Regards,
Jakub Kubacki
Ruby on Rails Developer
netguru.co

**Comment by gogi** [comment]
Specs added :smiley_cat: 

62ff634c8e983198cde620b5678e65045e83f456
1e1b18a4357909dd386bfe8b82dfff73c5cc750a

**Comment by gogi** [comment]
specs refactored :crown: :+1: 

143b395e657a2477c419d507274d4e5d64f336a4

**Comment by jkubacki** [comment]
Nice one!
