### ISSUE TITLE
Reclaim button

### ISSUE THREAD

**Issue by jkubacki** [fantasygame/campaigns#3]
Reclaim sold item
After click:
* Remove sold money from campaign
* Remove sold for from item
* Set sold to false

**Comment by gogi** [comment]
Done. But the field 'hero' remains nul after reclaim an item. I figured, I will add new variable that stores name of last owner and after reclaim sets it as hero.

**Comment by jkubacki** [comment]
As I commented in your commit - this should be an association. 

You're still implementing this feature. So it is not closed yet ;)
