### ISSUE TITLE
Count of played games in user profile page

### ISSUE THREAD

**Issue by jkubacki** [fantasygame/campaigns#5]
It should count user games count based of his heroes games. No doubles for game in which there were multiple heroes of one user.

**Comment by jkubacki** [comment]
Nice! But I also played those games ;(
http://content.screencast.com/users/jakub.kubacki/folders/Jing/media/cb9e86af-3e16-4839-a50d-bb7c0c661e38/00000069.png

**Comment by gogi** [comment]
FUCK OFF!

2015-05-31 12:59 GMT+02:00 Jakub Kubacki <notifications@github.com>:

> Reopened #5 <https://github.com/fantasygame/campaigns/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fantasygame/campaigns/issues/5#event-318100723>.
>



-- 
Pozdrawiam,

Małgorzata Grobelska

**Comment by jkubacki** [comment]
:-1:

**Comment by gogi** [comment]
bo to działa tylko dla prawdziwych memberów, a nie dla miszczów :game_die:

**Comment by jkubacki** [comment]
I don't understand :(

**Comment by gogi** [comment]
You are right - I'm searching through heroes, so game master will be always
omitted - I have to change it

2015-05-31 13:08 GMT+02:00 Jakub Kubacki <notifications@github.com>:

> I don't understand :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fantasygame/campaigns/issues/5#issuecomment-107156536>
> .
>



-- 
Pozdrawiam,

Małgorzata Grobelska

**Comment by jkubacki** [comment]
Bug! http://screencast.com/t/DeO2yS2ggF Ian didn't play all 22 games. ;)

**Comment by gogi** [comment]
Fuuu! You are right - it counts all games :/
I'm on it!

2015-05-31 16:10 GMT+02:00 Jakub Kubacki <notifications@github.com>:

> Bug! http://screencast.com/t/DeO2yS2ggF Ian didn't play all 22 games. ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fantasygame/campaigns/issues/5#issuecomment-107191755>
> .
>



-- 
Pozdrawiam,

Małgorzata Grobelska

**Comment by gogi** [comment]
Bug fixed. I didn't specify what the method should return, so at the end it gave gack array of all games it was iterate through.

467601723dbe4d96cc5c5e2a12bcd7b25c9b909d

**Comment by jkubacki** [comment]
Nice! Could you also add count of all games that user played here in users index?

**Comment by gogi** [comment]
Sure, but it would be all played games and not games played in specific
campaign.

2015-06-01 12:05 GMT+02:00 Jakub Kubacki <notifications@github.com>:

> Nice! Could you also add count of all games that user played here in users
> index?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fantasygame/campaigns/issues/5#issuecomment-107386492>
> .
>



-- 
Pozdrawiam,

Małgorzata Grobelska

**Comment by jkubacki** [comment]
Yeah, that's what I have on my mind.

**Comment by jkubacki** [comment]
And also could you add badge with count of all played games in user show? :)

**Comment by gogi** [comment]
All done :)

badge: edb6fc4941ee6ba40a5e228da1cd2201dc5b9014
